// Code generated by qtc from "seed.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line query/seed.qtpl:1
package query

//line query/seed.qtpl:2
import "strings"

//line query/seed.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line query/seed.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line query/seed.qtpl:4
func StreamInsertData(qw422016 *qt422016.Writer, schemaName, tableName, returning string, columns []string, rows int) {
//line query/seed.qtpl:4
	qw422016.N().S(`
    INSERT INTO `)
//line query/seed.qtpl:5
	qw422016.E().S(schemaName)
//line query/seed.qtpl:5
	qw422016.N().S(`.`)
//line query/seed.qtpl:5
	qw422016.E().S(tableName)
//line query/seed.qtpl:5
	qw422016.N().S(` (`)
//line query/seed.qtpl:5
	qw422016.E().S(strings.Join(columns, ","))
//line query/seed.qtpl:5
	qw422016.N().S(`)
    VALUES `)
//line query/seed.qtpl:6
	qw422016.E().S(renderValues(len(columns), rows))
//line query/seed.qtpl:6
	qw422016.N().S(` ON CONFLICT DO NOTHING
    `)
//line query/seed.qtpl:7
	if returning != "" {
//line query/seed.qtpl:7
		qw422016.N().S(` RETURNING `)
//line query/seed.qtpl:7
		qw422016.E().S(returning)
//line query/seed.qtpl:7
	}
//line query/seed.qtpl:7
	qw422016.N().S(`
`)
//line query/seed.qtpl:8
}

//line query/seed.qtpl:8
func WriteInsertData(qq422016 qtio422016.Writer, schemaName, tableName, returning string, columns []string, rows int) {
//line query/seed.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line query/seed.qtpl:8
	StreamInsertData(qw422016, schemaName, tableName, returning, columns, rows)
//line query/seed.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line query/seed.qtpl:8
}

//line query/seed.qtpl:8
func InsertData(schemaName, tableName, returning string, columns []string, rows int) string {
//line query/seed.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line query/seed.qtpl:8
	WriteInsertData(qb422016, schemaName, tableName, returning, columns, rows)
//line query/seed.qtpl:8
	qs422016 := string(qb422016.B)
//line query/seed.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line query/seed.qtpl:8
	return qs422016
//line query/seed.qtpl:8
}
